export type User = {
  name: string;
  firstName: string;
  lastName: string;
  email: string;
  gender: any;
  phoneNumber: string;
  address: any;
  organizationId: string;
  organization: Organization;
  verificationCode: string;
  roleId: string;
  applicationRole: ApplicationRole;
  profilePicture: any;
  withInNigeria: boolean;
  age: number;
  income: number;
  cityId: any;
  isAViewingAgent: boolean;
  countryId: any;
  city: any;
  lastLoginDate: string;
  dateOfBirth: string;
  isActive: boolean;
  isDeleted: boolean;
  affordability: any;
  verifications: any[];
  accounts: any[];
  id: string;
  createdBy: string;
  dateCreated: string;
  dateLastModified: string;
  lastModifiedBy: any;
};

export type Organization = {
  name: string;
  address: string;
  description: string;
  emailAddress: string;
  phoneNumber: string;
  mobileNumber: any;
  logo: string;
  coverImage: string;
  brandColorCode: string;
  bankName: string;
  accountNumber: string;
  bankCode: string;
  longitude: number;
  latitude: number;
  yearsInOperation: number;
  city: any;
  documents: any;
  organizationType: any;
  estates: any[];
  propertyCount: any;
  partnerships: any;
  houses: any[];
  id: string;
  createdBy: string;
  dateCreated: string;
  dateLastModified: string;
  lastModifiedBy: string;
};

export type ApplicationRole = {
  id: string;
  name: string;
  access: string;
  description: string;
  identifier: any;
  createdBy: string;
  dateCreated: string;
  lastModifiedBy: any;
  dateLastModified: string;
};
