export const DEFAULT_TRANSACTIONS = "DEFAULT_TRANSACTIONS";
export const TRANSACTION_SUMMARY = "TRANSACTION_SUMMARY";
export const SUCCESSFUL_TRANSACTIONS = "SUCCESSFUL_TRANSACTIONS";
export const EXPECTED_TRANSACTIONS = "EXPECTED_TRANSACTIONS";
